http:
  port: "8081"
  
sfdc:
  username: "asish.aash@gmail.com"
  password: "Asish@95"
  token: "6tYJT46GoG9vVYGkeWMzCaPc"  
  
file:
  accountsDir: "D:/NJC Assignments/New folder/MUFundamentals4.3_studentFiles_12may2020/MUFundamentals4.3_studentFiles_12may2020/resources"  
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"  